import type {ReactNode} from "react";
import {office,canonical,pillars,privacy,social} from "@/legal-content";
const mapQuery=encodeURIComponent(office.address+", "+office.city+" - "+office.state+", "+office.zip);
const icons:Record<string,ReactNode>={
Instagram:<svg viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="currentColor" strokeWidth="1.6" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4.2"/><circle cx="17.4" cy="6.6" r="1"/></svg>,
X:<svg viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="currentColor" strokeWidth="1.6" aria-hidden="true"><path d="M4 4l16 16M20 4L4 20"/></svg>,
Google:<svg viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="currentColor" strokeWidth="1.6" aria-hidden="true"><circle cx="12" cy="10" r="3.2"/><path d="M12 21c4-4 7-7.5 7-11a7 7 0 1 0-14 0c0 3.5 3 7 7 11z"/></svg>
};
export function Social(){return <ul className="social" aria-label="Redes e perfis oficiais">{social.map(s=><li key={s.name}><a href={s.href} target="_blank" rel="noreferrer" aria-label={s.name+" oficial · "+s.handle+" (abre em nova guia)"}>{icons[s.name]}<span>{s.name} {s.handle} ↗</span></a></li>)}</ul>;}
export function Nap(){return <address><strong>{office.name}</strong><br/>{office.address}<br/>{office.city}/{office.state} · CEP {office.zip}<br/><a href={"tel:"+office.tel}>{office.phone}</a><br/>Dr. Márcio Jr. França · OAB/AC 2882</address>;}
export function Layout({children}:{children:ReactNode}){return <div className="legal"><a className="skip" href="#conteudo">Ir ao conteúdo</a><header className="legal-header"><a className="brand" href="/"><img src="/assets/brand/monograma.webp" width="64" height="64" alt="Monograma MF"/><span>Márcio Jr. França<small>ADVOCACIA JURÍDICA</small></span></a><nav aria-label="Navegação principal"><a href="/">Início</a><a href="/#areas">Áreas</a><a href="/regularizacao-fundiaria-acre/">Regularização fundiária</a><a href="/advogado-previdenciario-rio-branco/">Previdenciário</a><a href="/contato/">Contato</a></nav></header><main id="conteudo">{children}</main><footer><Nap/><div><a href="/contato/">Canais oficiais</a><a href="/">Início</a><a href="/privacidade/">Privacidade</a><p className="section-label">Redes e perfis oficiais</p><Social/><p>Conteúdo informativo. Cada situação exige análise individual.</p></div></footer><a className="mobile-contact" href={office.whatsapp} aria-label="WhatsApp · canal oficial (abre o WhatsApp)">WhatsApp · canal oficial ↗</a></div>;}
export function Contact({heading=true}:{heading?:boolean}){return <section className="contact section" id="contato"><div>{heading&&<h2>Canais oficiais, atendimento próximo.</h2>}<p>Atendimento presencial em Rio Branco, mediante agendamento, e remoto quando cabível. Fale pelos canais oficiais para combinar a forma de atendimento.</p><Nap/><a className="contact-link whatsapp-link" href={office.whatsapp} aria-label="WhatsApp oficial (abre o WhatsApp)">WhatsApp oficial ↗</a><p className="section-label">Redes e perfis oficiais</p><Social/><p className="note">Não envie senhas, códigos de acesso ou documentos sensíveis no primeiro contato.</p></div><iframe title="Mapa do endereço de atendimento em Rio Branco" src={"https://www.google.com/maps?q="+mapQuery+"&output=embed"} loading="lazy" width="600" height="380" referrerPolicy="no-referrer-when-downgrade"/></section>;}
export function Schema({faq,crumbs}:{faq?:string[][];crumbs?:[string,string][]}){const data={"@context":"https://schema.org","@graph":[{"@type":"LegalService","@id":canonical+"/#legalservice",name:office.name,url:canonical+"/",description:"Advocacia em Rio Branco e no Acre. Orientação em regularização fundiária, REURB, previdenciário e outras áreas.",telephone:office.tel,image:canonical+"/assets/brand/og.jpg",logo:canonical+"/assets/brand/monograma.webp",address:{"@type":"PostalAddress",streetAddress:office.address,addressLocality:office.city,addressRegion:office.state,postalCode:office.zip,addressCountry:"BR"},areaServed:{"@type":"State",name:"Acre"},employee:{"@id":canonical+"/#advogado"},knowsAbout:["Regularização fundiária","REURB","Direito previdenciário","Aposentadoria rural"]},{"@type":"Person","@id":canonical+"/#advogado",name:office.lawyer,jobTitle:"Advogado",identifier:office.oab,image:canonical+"/assets/brand/retrato-sobre.webp",worksFor:{"@id":canonical+"/#legalservice"}},{"@type":"WebSite","@id":canonical+"/#website",url:canonical+"/",name:office.name,inLanguage:"pt-BR",publisher:{"@id":canonical+"/#legalservice"}},...(crumbs?[{"@type":"BreadcrumbList",itemListElement:crumbs.map(([name,path],i)=>({"@type":"ListItem",position:i+1,name,item:canonical+path}))}]:[]),...(faq?[{"@type":"FAQPage",mainEntity:faq.map(([q,a])=>({"@type":"Question",name:q,acceptedAnswer:{"@type":"Answer",text:a}}))}]:[])]};return <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(data).replace(/</g,"\\u003c")}}/>;}
export function Privacy(){return <Layout><Schema crumbs={[["Início","/"],[privacy.h1,"/privacidade/"]]}/><section className="section contact-title"><p className="eyebrow">LGPD · LEI Nº 13.709/2018</p><h1>{privacy.h1}</h1><p className="lead">{privacy.intro}</p></section><div className="reading">{privacy.sections.map(([h,t])=><section key={h}><h2>{h}</h2><p>{t}</p></section>)}<p className="note">Última atualização: setembro de 2026.</p></div><Contact/></Layout>;}
export function Pillar({index}:{index:number}){const p=pillars[index];return <Layout><Schema faq={p.faq} crumbs={[["Início","/"],[p.h1,"/"+p.slug+"/"]]}/><section className="pillar-hero section"><div><a href="/#areas">Áreas de atuação</a><h1>{p.h1}</h1><p className="lead">{p.intro}</p><a className="primary" href="/contato/">Fale pelos canais oficiais ↗</a></div><img src="/assets/brand/identidade-clara.webp" width="1346" height="560" alt="Identidade visual da Advocacia Márcio Jr. França em Rio Branco, Acre" loading="lazy"/></section><div className="reading">{p.sections.map(([h,t])=><section key={h}><h2>{h}</h2><p>{t}</p></section>)}<section><h2>Perguntas frequentes</h2>{p.faq.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</section><p className="note">Referência: <a href={p.source}>{p.sourceLabel}</a>. Informação geral, sem promessa de resultado.</p><nav className="related" aria-label="Conteúdos relacionados">{pillars.filter(x=>x.slug!==p.slug).map(x=><a key={x.slug} href={"/"+x.slug+"/"}>{x.h1} ↗</a>)}</nav></div><Contact/></Layout>;}
