
import {Layout,Contact,Schema} from "@/components/Institutional";
import {pillars,pageHead,portraitAlt} from "@/legal-content";

export default function Home(){return <Layout><Schema/><section className="hero"><div className="hero-copy"><p className="eyebrow">RIO BRANCO / ACRE</p><h1>Advocacia em Rio Branco.<br/><em>Clareza para o próximo passo.</em></h1><p className="lead">Orientação jurídica em regularização fundiária, previdenciário e outras áreas. Análise dos fatos, dos documentos e das alternativas de cada caso.</p><div className="hero-actions"><a className="primary" href="#areas">Conheça as áreas ↓</a><a className="secondary" href="/contato/">Canais oficiais ↗</a></div><p className="credentials">DR. MÁRCIO JR. FRANÇA · OAB/AC 2882</p></div><figure className="hero-portrait"><img src="/assets/brand/retrato-hero.webp" width="1145" height="1374" alt={portraitAlt} fetchPriority="high"/><figcaption><span>Precedentes · Processo · Prática Forense</span>Presença no Acre. Atendimento com atenção ao seu contexto.</figcaption></figure></section><div className="proof"><span>OAB/AC <b>2882</b></span><span><b>+15 anos</b> de atuação · desde 2010</span><span>Atendimento <b>no Acre</b></span><a href="https://www.google.com/maps/search/?api=1&query=M%C3%A1rcio+Jr.+Fran%C3%A7a+Advocacia+Jur%C3%ADdica+Rio+Branco+AC" target="_blank" rel="noreferrer">Perfil e avaliações no <b>Google ↗</b></a></div>
<section className="section introduction"><h2>Orientação começa por entender sua situação.</h2><div><p>Quem busca um advogado em Rio Branco precisa saber por onde começar. O primeiro passo é compreender os fatos e organizar os documentos disponíveis.</p><a className="text-link" href="/contato/">Saiba como funciona o atendimento ↗</a></div></section>
<section className="section areas" id="areas"><div className="section-title"><p className="eyebrow">ÁREAS DE ATUAÇÃO</p><h2>Questões da terra.<br/>Direitos de quem trabalha.<br/><em>Decisões da vida.</em></h2></div><div className="area-grid">{pillars.map((p,i)=><a className="area-card" href={"/"+p.slug+"/"} key={p.slug}><span>0{i+1} ↗</span><h3>{p.h1}</h3><p>{["Terra sem título, documentos e histórico da ocupação.","Entenda a regularização de núcleos urbanos informais.","Pedidos, exigências e decisões do INSS.","Organização da trajetória e dos documentos do trabalho rural."][i]}</p></a>)}</div><p className="other">Também atuamos nas áreas Cível, Consumidor, Família, Criminal, Tributária e Ambiental. <a href="/contato/">Fale pelos canais oficiais.</a></p></section>
<section className="section process"><div><h2>Procedimentos explicados.<br/>Sem atalhos ou promessas.</h2><p>REURB, titulação e usucapião têm requisitos distintos. No previdenciário, o histórico de trabalho e os documentos orientam a análise.</p></div><ol><li><b>01 · Compreender</b><p>Relato da situação e identificação da dúvida.</p></li><li><b>02 · Conferir</b><p>Organização e leitura dos documentos disponíveis.</p></li><li><b>03 · Orientar</b><p>Explicação das alternativas e das providências cabíveis.</p></li></ol></section>
<section className="section about"><img src="/assets/brand/retrato-sobre.webp" width="526" height="526" alt={portraitAlt} loading="lazy"/><div><p className="eyebrow">QUEM ATENDE VOCÊ</p><h2>Dr. Márcio Jr. França</h2><p className="oab">ADVOGADO · OAB/AC 2882</p><p>Atuação desde 2010, com base em Rio Branco e atendimento no Acre. O trabalho reúne análise técnica, atenção aos documentos e explicações em linguagem clara.</p><p>O atendimento presencial é combinado previamente. A modalidade remota pode ser utilizada conforme as necessidades do caso.</p><a className="text-link" href="/contato/">Conheça os canais de atendimento ↗</a></div></section><Contact/></Layout>;}
